import { randomUUID } from "node:crypto";

import { env } from "../../../config/env";
import { logger } from "../../../logger";

export type GeneratedVariant = {
  name: string;
  branchName: string;
  pullRequestTitle: string;
  pullRequestBody: string;
};

export type GenerateVariantsInput = {
  experimentId: string;
  repoFullName: string;
  goal: string;
  allowList: string[];
};

export interface VariantGenerator {
  generate(input: GenerateVariantsInput): Promise<GeneratedVariant[]>;
}

export class E2BCodexVariantGenerator implements VariantGenerator {
  async generate(input: GenerateVariantsInput): Promise<GeneratedVariant[]> {
    if (!env.E2B_API_KEY) {
      logger.warn("E2B is not configured; returning local demo variant plans", {
        module: "e2b-codex",
        experimentId: input.experimentId
      });
    }

    return ["Variant A", "Variant B"].map((name) => {
      const suffix = randomUUID().slice(0, 8);

      return {
        name,
        branchName: `growloop/${input.experimentId}/${suffix}`,
        pullRequestTitle: `${name}: ${input.goal}`,
        pullRequestBody: [
          "Generated by Growloop.",
          "",
          `Goal: ${input.goal}`,
          `Allowed paths: ${input.allowList.join(", ") || "not configured"}`
        ].join("\n")
      };
    });
  }
}
