import { randomUUID } from "node:crypto";

import { Sandbox } from "e2b/dist/index.mjs";

import { env } from "../../../config/env";
import { logger } from "../../../logger";
import type { GitHubInstallationTokenProvider } from "../github/github-app-client";

export type GeneratedVariant = {
  name: string;
  branchName: string;
  pullRequestTitle: string;
  pullRequestBody: string;
};

export type GenerateVariantsInput = {
  experimentId: string;
  repoFullName: string;
  goal: string;
  allowList: string[];
  variantNames?: string[];
};

export interface VariantGenerator {
  generate(input: GenerateVariantsInput): Promise<GeneratedVariant[]>;
}

const REPO_PATH = "/home/user/repo";
const GITHUB_USERNAME = "x-access-token";

export class E2BCodexVariantGenerator implements VariantGenerator {
  constructor(private readonly github: GitHubInstallationTokenProvider) {}

  async generate(input: GenerateVariantsInput): Promise<GeneratedVariant[]> {
    const variants = input.variantNames?.length ? input.variantNames : ["Variant A", "Variant B"];

    if (!env.E2B_API_KEY) {
      logger.warn("E2B is not configured; returning local demo variant plans", {
        module: "e2b-codex",
        experimentId: input.experimentId
      });

      return variants.map((name) => this.createPlan(input, name));
    }

    const token = await this.github.createInstallationToken();
    const plans: GeneratedVariant[] = [];

    for (const name of variants) {
      const plan = this.createPlan(input, name);
      await this.createVariantBranch(input, plan, token);
      plans.push(plan);
    }

    return plans;
  }

  private createPlan(input: GenerateVariantsInput, name: string): GeneratedVariant {
    const suffix = randomUUID().slice(0, 8);

    return {
      name,
      branchName: `growloop/${input.experimentId}/${suffix}`,
      pullRequestTitle: `${name}: ${input.goal}`,
      pullRequestBody: [
        "Generated by Growloop.",
        "",
        `Goal: ${input.goal}`,
        `Allowed paths: ${input.allowList.join(", ") || "not configured"}`,
        env.OPENAI_API_KEY
          ? "Implementation was generated in an E2B Codex sandbox."
          : "Sandbox smoke mode: Codex API key is not configured yet."
      ].join("\n")
    };
  }

  private async createVariantBranch(
    input: GenerateVariantsInput,
    plan: GeneratedVariant,
    githubToken: string
  ): Promise<void> {
    const sandbox = await Sandbox.create(env.E2B_TEMPLATE, {
      apiKey: env.E2B_API_KEY,
      timeoutMs: env.E2B_SANDBOX_TIMEOUT_MS,
      envs: {
        ...(env.OPENAI_API_KEY ? { OPENAI_API_KEY: env.OPENAI_API_KEY } : {})
      }
    });

    logger.info("Created E2B sandbox for experiment variant", {
      module: "e2b-codex",
      experimentId: input.experimentId,
      repoFullName: input.repoFullName,
      branchName: plan.branchName,
      sandboxId: sandbox.sandboxId
    });

    try {
      await sandbox.git.clone(`https://github.com/${input.repoFullName}.git`, {
        path: REPO_PATH,
        branch: "main",
        depth: 1,
        username: GITHUB_USERNAME,
        password: githubToken,
        timeoutMs: 120_000
      });

      await sandbox.git.createBranch(REPO_PATH, plan.branchName);

      if (env.OPENAI_API_KEY) {
        await this.runCodex(sandbox, input, plan);
      } else {
        await this.writeSmokeChange(sandbox, input, plan);
      }

      await this.ensureChangesExist(sandbox, plan);
      await sandbox.git.configureUser("growloopbot[bot]", "growloopbot[bot]@users.noreply.github.com", {
        scope: "local",
        path: REPO_PATH
      });
      await sandbox.git.add(REPO_PATH, { all: true });
      await sandbox.git.commit(REPO_PATH, `experiment: ${plan.name.toLowerCase()} for ${input.goal}`, {
        authorName: "growloopbot[bot]",
        authorEmail: "growloopbot[bot]@users.noreply.github.com"
      });
      await sandbox.git.push(REPO_PATH, {
        remote: "origin",
        branch: plan.branchName,
        username: GITHUB_USERNAME,
        password: githubToken,
        timeoutMs: 120_000
      });

      logger.info("Pushed E2B-generated experiment branch", {
        module: "e2b-codex",
        experimentId: input.experimentId,
        repoFullName: input.repoFullName,
        branchName: plan.branchName,
        sandboxId: sandbox.sandboxId
      });
    } finally {
      await sandbox.kill().catch((error: unknown) => {
        logger.warn("Failed to kill E2B sandbox", {
          module: "e2b-codex",
          experimentId: input.experimentId,
          branchName: plan.branchName,
          error: getErrorMessage(error)
        });
      });
    }
  }

  private async runCodex(
    sandbox: Sandbox,
    input: GenerateVariantsInput,
    plan: GeneratedVariant
  ): Promise<void> {
    const prompt = [
      "You are implementing a Growloop conversion experiment variant.",
      `Variant name: ${plan.name}`,
      `Goal: ${input.goal}`,
      `Allowed paths: ${input.allowList.join(", ") || "none provided"}`,
      "",
      "Keep the change small, reversible, and production-safe.",
      "Only edit files needed for this experiment variant.",
      "Do not commit, push, or open a pull request."
    ].join("\n");

    await sandbox.commands.run(`${env.CODEX_COMMAND} exec --full-auto --skip-git-repo-check -C ${REPO_PATH} ${shellQuote(prompt)}`, {
      timeoutMs: 300_000
    });
  }

  private async writeSmokeChange(
    sandbox: Sandbox,
    input: GenerateVariantsInput,
    plan: GeneratedVariant
  ): Promise<void> {
    const filePath = `.growloop-smoke/${plan.branchName.replaceAll("/", "-")}.md`;
    const content = [
      `# ${plan.name}`,
      "",
      "Created by Growloop inside an E2B sandbox.",
      "",
      `Experiment: ${input.experimentId}`,
      `Goal: ${input.goal}`,
      `Allowed paths: ${input.allowList.join(", ") || "not configured"}`
    ].join("\n");

    await sandbox.commands.run(
      `mkdir -p ${REPO_PATH}/.growloop-smoke && printf %s ${shellQuote(content)} > ${REPO_PATH}/${filePath}`,
      { timeoutMs: 30_000 }
    );
  }

  private async ensureChangesExist(sandbox: Sandbox, plan: GeneratedVariant): Promise<void> {
    const status = await sandbox.git.status(REPO_PATH);

    if (!status.hasChanges) {
      throw new Error(`No repository changes were generated for ${plan.name}`);
    }
  }
}

function shellQuote(value: string) {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : "unknown error";
}
